In [2]:
import pandas as pd

In [10]:
df_8000 = pd.read_csv("8000_Extended_Noisy.csv")
df_tracker = pd.read_csv("Tracker_Noisy.csv")
df_budget = pd.read_csv("Budget_Noisy.csv")
df_expenses = pd.read_csv("Expenses_Noisy.csv")
df_income = pd.read_csv("Income_Noisy.csv")
# Xem kích thước dữ liệu
print("\n KÍCH THƯỚC DỮ LIỆU")
print("8000:", df_8000.shape)
print("Tracker:", df_tracker.shape)
print("Budget:", df_budget.shape)
print("Expenses:", df_expenses.shape)
print("Income:", df_income.shape)
# Xem thông tin dữ liệu
print("\n THÔNG TIN DỮ LIỆU")
df_8000.info()
df_tracker.info()
df_budget.info()
df_expenses.info()
df_income.info()
# Xem thống kê mô tả dữ liệu
print("\n THỐNG KÊ MÔ TẢ")
display(df_8000.describe().round(2)) #Thống kê mô tả cột số tiền
display(df_tracker.describe().round(2)) #Thống kê mô tả các chỉ số tài chính
# Kiểm tra giá trị khuyết trống thiếu
print("\n GIÁ TRỊ KHUYẾT TRỐNG THIẾU")
print(df_8000.isnull().sum())
print(df_tracker.isnull().sum())
print(df_budget.isnull().sum())
print(df_expenses.isnull().sum())
print(df_income.isnull().sum())
# Kiểm tra trùng lặp
print("\n DỮ LIỆU TRÙNG LẶP")
print(df_8000.duplicated().sum())
print(df_tracker.duplicated().sum())
print(df_budget.duplicated().sum())
print(df_expenses.duplicated().sum())
print(df_income.duplicated().sum()) 
# Kiểm tra các danh mục chi tiêu
print("\n CATEGORY BẤT THƯỜNG")
print(df_8000["Category"].value_counts())
# Kiểm tra Credit Score bất thường
print("\n CREDIT SCORE BẤT THƯỜNG")
print("Số lượng:", (df_tracker["credit_score"] < 0).sum())
# Khám phá dữ liệu ngày tháng
print("\n DỮ LIỆU NGÀY THÁNG")
print(df_expenses["date_time"].head())
print(df_income["date_time"].head())

 KÍCH THƯỚC DỮ LIỆU
8000: (8000, 15)
Tracker: (3000, 25)
Budget: (3608, 3)
Expenses: (938, 8)
Income: (349, 8)

 THÔNG TIN DỮ LIỆU
<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             8000 non-null   str
 1   Description      8000 non-null   str
 2   Amount           7596 non-null   float64
 3   Category         7695 non-null   str
 4   PaymentMethod    8000 non-null   str
 5   Location         8000 non-null   str
 6   AccountType      8000 non-null   str
 7   TransactionType  8000 non-null   str
 8   DeviceUsed       8000 non-null   str
 9   Currency         8000 non-null   str
 10  MerchantType     8000 non-null   str
 11  LoyaltyProgram   8000 non-null   str
 12  Weekday          8000 non-null   str
 13  Month            8000 non-null   str
 14  TimeOfDay        8000 non-null   str
dtypes: float64(1), str(14)
memory usage: 937.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    3000 non-null   str
 1   user_id                 3000 non-null   int64
 2   monthly_income          2820 non-null   float64
 3   monthly_expense_total   3000 non-null   float64
 4   savings_rate            3000 non-null   float64
 5   budget_goal             3000 non-null   float64
 6   financial_scenario      3000 non-null   str
 7   credit_score            2817 non-null   float64
 8   debt_to_income_ratio    2813 non-null   float64
 9   loan_payment            3000 non-null   float64
 10  investment_amount       3000 non-null   float64
 11  subscription_services   3000 non-null   int64
 12  emergency_fund          3000 non-null   float64
 13  transaction_count       3000 non-null   int64
 14  fraud_flag              3000 non-null   int64
 15  discretionary_spending  3000 non-null   float64
 16  essential_spending      3000 non-null   float64
 17  income_type             3000 non-null   str
 18  rent_or_mortgage        3000 non-null   float64
 19  category                3000 non-null   str
 20  cash_flow_status        3000 non-null   str
 21  financial_advice_score  3000 non-null   float64
 22  financial_stress_level  2829 non-null   str
 23  actual_savings          3000 non-null   float64
 24  savings_goal_met        3000 non-null   int64
dtypes: float64(14), int64(5), str(6)
memory usage: 586.1 KB
<class 'pandas.DataFrame'>
RangeIndex: 3608 entries, 0 to 3607
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      3608 non-null   str
 1   category  3608 non-null   str
 2   amount    3507 non-null   float64
dtypes: float64(1), str(2)
memory usage: 84.7 KB
<class 'pandas.DataFrame'>
RangeIndex: 938 entries, 0 to 937
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date_time  938 non-null    str
 1   category   938 non-null    str
 2   account    938 non-null    str
 3   amount     938 non-null    float64
 4   currency   938 non-null    str
 5   tags       938 non-null    str
 6   Amount     0 non-null      float64
 7   Category   0 non-null      float64
dtypes: float64(3), str(5)
memory usage: 58.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 349 entries, 0 to 348
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date_time  349 non-null    str
 1   category   349 non-null    str
 2   account    349 non-null    str
 3   amount     349 non-null    float64
 4   currency   349 non-null    str
 5   tags       349 non-null    str
 6   Amount     0 non-null      float64
 7   Category   0 non-null      float64
dtypes: float64(3), str(5)
memory usage: 21.9 KB

 THỐNG KÊ MÔ TẢ

            Amount
count      7596.00
mean      23701.48
std      283676.10
min          54.11
25%         924.62
50%        3308.08
75%       11355.96
max    13129482.00

,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,credit_score,debt_to_income_ratio,loan_payment,investment_amount,subscription_services,emergency_fund,transaction_count,fraud_flag,discretionary_spending,essential_spending,rent_or_mortgage,financial_advice_score,actual_savings,savings_goal_met
count,3000.00,2820.00,3000.00,3000.00,3000.00,2817.00,2813.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00
mean,1498.70,3998.05,3011.68,0.23,2811.07,671.21,0.35,508.58,400.61,4.97,1005.35,59.53,0.02,500.81,2215.59,1211.90,50.07,1156.42,0.09
std,287.35,998.06,801.15,0.10,490.86,131.85,0.15,199.44,235.36,2.56,485.78,23.10,0.15,199.80,596.27,400.48,29.09,1039.60,0.29
min,1000.00,685.28,159.21,0.05,1175.57,-999.00,0.10,0.00,0.00,1.00,0.00,20.00,0.00,0.00,1000.00,300.00,0.10,0.00,0.00
25%,1248.75,3354.75,2473.20,0.14,2481.96,645.00,0.23,375.34,234.78,3.00,674.01,38.75,0.00,361.56,1807.24,933.53,25.10,144.96,0.00
50%,1496.50,4002.89,3023.81,0.23,2822.28,679.00,0.35,508.57,388.08,5.00,1010.48,60.00,0.00,496.34,2215.70,1213.60,48.70,1032.81,0.00
75%,1749.00,4650.16,3555.50,0.31,3131.00,713.00,0.48,638.47,559.84,7.00,1337.82,79.00,0.00,640.10,2624.68,1482.86,76.10,1821.51,0.00
max,1999.00,7407.94,5853.20,0.40,4386.50,847.00,0.60,1176.88,1292.30,9.00,2585.36,99.00,1.00,1158.74,4245.90,2614.62,100.00,6589.66,1.00

 GIÁ TRỊ KHUYẾT TRỐNG THIẾU
Date                 0
Description          0
Amount             404
Category           305
PaymentMethod        0
Location             0
AccountType          0
TransactionType      0
DeviceUsed           0
Currency             0
MerchantType         0
LoyaltyProgram       0
Weekday              0
Month                0
TimeOfDay            0
dtype: int64
date                        0
user_id                     0
monthly_income            180
monthly_expense_total       0
savings_rate                0
budget_goal                 0
financial_scenario          0
credit_score              183
debt_to_income_ratio      187
loan_payment                0
investment_amount           0
subscription_services       0
emergency_fund              0
transaction_count           0
fraud_flag                  0
discretionary_spending      0
essential_spending          0
income_type                 0
rent_or_mortgage            0
category                    0
cash_flow_status            0
financial_advice_score      0
financial_stress_level    171
actual_savings              0
savings_goal_met            0
dtype: int64
date          0
category      0
amount      101
dtype: int64
date_time      0
category       0
account        0
amount         0
currency       0
tags           0
Amount       938
Category     938
dtype: int64
date_time      0
category       0
account        0
amount         0
currency       0
tags           0
Amount       349
Category     349
dtype: int64

 DỮ LIỆU TRÙNG LẶP
0
0
0
149
0

 CATEGORY BẤT THƯỜNG
Category
Online Shopping    803
Entertainment      800
Food               785
Healthcare         769
Electronics        766
Travell_err        764
Transport          761
Biills             754
Grocerie$          750
Clothing           743
Name: count, dtype: int64

 CREDIT SCORE BẤT THƯỜNG
Số lượng: 15

 DỮ LIỆU NGÀY THÁNG
0    2025-11-30 00:00:00
1     ERR_DATE_FORMAT_99
2    2025-11-27 00:00:00
3    2025-11-27 00:00:00
4    2025-11-27 00:00:00
Name: date_time, dtype: str
0    2025-11-29 00:00:00
1    2025-11-29 00:00:00
2    2025-11-29 00:00:00
3    2025-11-29 00:00:00
4    2025-11-28 00:00:00
Name: date_time, dtype: str