In [5]:
%pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.5.0)
Requirement already satisfied: matplotlib in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HALO\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\HALO\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\HALO\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\HALO\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import numpy as np
import random
np.random.seed(42)
random.seed(42)
try: 
    df_expenses_raw = pd.read_csv('Expenses_clean.csv')
    df_income_raw = pd.read_csv('Income_clean.csv')
    df_budget_raw = pd.read_csv('budget_data.csv')
    df_tracker_raw = pd.read_csv('personal_finance_tracker_dataset.csv')
    df_8000_raw = pd.read_csv('personal_finance_dataset_8000_extended.csv')
except FileNotFoundError as e:
    print(f" Thiếu file trên hệ thống. Vui lòng cập nhật file vào! {e}")
    raise
# GÂY NHIỄU CHO CÁC FILE DỮ LIỆU
#1. Gây nhiễu file Expenses - Income - Budget
# Tạo ô trống ngẫu nhiên ở cột số tiền - Amount và danh mục - Category
mask_exp_amt = np.random.rand(len(df_expenses_raw)) < 0.05
mask_exp_cat = np.random.rand(len(df_expenses_raw)) < 0.04
mask_inc_amt = np.random.rand(len(df_income_raw)) < 0.05
mask_inc_cat = np.random.rand(len(df_income_raw)) < 0.05
df_budget_raw.loc[np.random.rand(len(df_budget_raw)) < 0.03, 'amount'] = np.nan
df_expenses_raw.loc[mask_exp_amt, 'Amount'] = np.nan
df_expenses_raw.loc[mask_exp_cat, 'Category'] = np.nan
df_income_raw.loc[mask_inc_amt, 'Amount'] = np.nan
df_income_raw.loc[mask_inc_cat, 'Category'] = np.nan
# Gây lỗi định dạng ngày tháng
df_expenses_raw['date_time'] = (df_expenses_raw['date_time'].astype(str).apply(lambda x: "ERR_DATE_FORMAT_99" if random.random() < 0.03 else x)
)
df_income_raw['date_time'] = df_income_raw['date_time'].astype(str).apply(lambda x: "ERR_DATE_FORMAT_99" if random.random() < 0.04 else x
)
#2. Gây nhiễu cho file 8000_extended
# Tạo giá trị trống khuyết thiếu ngẫu nhiên ở cột số tiền - Amount và danh mục - Category
mask_amt = np.random.rand(len(df_8000_raw)) < 0.05
mask_cat = np.random.rand(len(df_8000_raw)) < 0.04
df_8000_raw['Amount'] = df_8000_raw['Amount'].mask(mask_amt)
df_8000_raw['Category'] = df_8000_raw['Category'].mask(mask_cat)
# Tạo thêm giao dịch bất thường với dòng tiền lớn hơn thực tế
outlier_idx = np.random.choice(df_8000_raw.index, size = 50, replace = False)
df_8000_raw.loc[outlier_idx, 'Amount'] = df_8000_raw.loc[outlier_idx, 'Amount'] * 100
# Tạo lỗi kí tự và chính tả ở danh mục
df_8000_raw['Category'] = df_8000_raw['Category'].replace({'Travel': 'Travell_err', 'Grocery': 'Grocerie$', 'Bills': 'Biills'})
#3. Gây nhiễu cho file Trakcer_dataset
# Tạo giá trị trống hệ thống ở các đặc trưng cốt lõi
for col in ['monthly_income', 'credit_score', 'debt_to_income_ratio', 'financial_stress_level']:
    mask = np.random.rand(len(df_tracker_raw)) < 0.06
    df_tracker_raw[col] = df_tracker_raw[col].mask(mask)
# Giá trị vô lí cho điểm tín dụng
bad_idx = np.random.choice(df_tracker_raw.index, size = 15, replace = False)
df_tracker_raw.loc[bad_idx, 'credit_score'] = -999.0
# XUẤT CÁC FILE NHIỄU
df_income_raw.to_csv("Income_Noisy.csv", index = False)
df_8000_raw.to_csv("8000_Extended_Noisy.csv", index = False)
df_budget_raw.to_csv("Budget_Noisy.csv", index = False)
df_tracker_raw.to_csv("Tracker_Noisy.csv", index = False)
df_expenses_raw.to_csv("Expenses_Noisy.csv", index = False)

In [ ]:
df_8000 = pd.read_csv("8000_Extended_Noisy.csv")
df_tracker = pd.read_csv("Tracker_Noisy.csv")
df_budget = pd.read_csv("Budget_Noisy.csv")
df_expenses = pd.read_csv("Expenses_Noisy.csv")
df_income = pd.read_csv("Income_Noisy.csv")
# Xem kích thước dữ liệu
print("8000:", df_8000.shape)
print("Tracker:", df_tracker.shape)
print("Budget:", df_budget.shape)
print("Expenses:", df_expenses.shape)
print("Income:", df_income.shape)
#Xem thông tin dữ liệu
df_8000.info()
df_tracker.info()
#Xem thống kê mô tả dữ liệu
display(df_8000.describe().round(2)) #Thống kê mô tả cột số tiền
display(df_tracker.describe().round(2)) #Thống kê mô tả các chỉ số tài chính

8000: (8000, 15)
Tracker: (3000, 25)
Budget: (3608, 3)
Expenses: (938, 8)
Income: (349, 8)
<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             8000 non-null   str
 1   Description      8000 non-null   str
 2   Amount           7596 non-null   float64
 3   Category         7695 non-null   str
 4   PaymentMethod    8000 non-null   str
 5   Location         8000 non-null   str
 6   AccountType      8000 non-null   str
 7   TransactionType  8000 non-null   str
 8   DeviceUsed       8000 non-null   str
 9   Currency         8000 non-null   str
 10  MerchantType     8000 non-null   str
 11  LoyaltyProgram   8000 non-null   str
 12  Weekday          8000 non-null   str
 13  Month            8000 non-null   str
 14  TimeOfDay        8000 non-null   str
dtypes: float64(1), str(14)
memory usage: 937.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    3000 non-null   str
 1   user_id                 3000 non-null   int64
 2   monthly_income          2820 non-null   float64
 3   monthly_expense_total   3000 non-null   float64
 4   savings_rate            3000 non-null   float64
 5   budget_goal             3000 non-null   float64
 6   financial_scenario      3000 non-null   str
 7   credit_score            2817 non-null   float64
 8   debt_to_income_ratio    2813 non-null   float64
 9   loan_payment            3000 non-null   float64
 10  investment_amount       3000 non-null   float64
 11  subscription_services   3000 non-null   int64
 12  emergency_fund          3000 non-null   float64
 13  transaction_count       3000 non-null   int64
 14  fraud_flag              3000 non-null   int64
 15  discretionary_spending  3000 non-null   float64
 16  essential_spending      3000 non-null   float64
 17  income_type             3000 non-null   str
 18  rent_or_mortgage        3000 non-null   float64
 19  category                3000 non-null   str
 20  cash_flow_status        3000 non-null   str
 21  financial_advice_score  3000 non-null   float64
 22  financial_stress_level  2829 non-null   str
 23  actual_savings          3000 non-null   float64
 24  savings_goal_met        3000 non-null   int64
dtypes: float64(14), int64(5), str(6)
memory usage: 586.1 KB

            Amount
count      7596.00
mean      23701.48
std      283676.10
min          54.11
25%         924.62
50%        3308.08
75%       11355.96
max    13129482.00

,user_id,monthly_income,monthly_expense_total,savings_rate,budget_goal,credit_score,debt_to_income_ratio,loan_payment,investment_amount,subscription_services,emergency_fund,transaction_count,fraud_flag,discretionary_spending,essential_spending,rent_or_mortgage,financial_advice_score,actual_savings,savings_goal_met
count,3000.00,2820.00,3000.00,3000.00,3000.00,2817.00,2813.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00
mean,1498.70,3998.05,3011.68,0.23,2811.07,671.21,0.35,508.58,400.61,4.97,1005.35,59.53,0.02,500.81,2215.59,1211.90,50.07,1156.42,0.09
std,287.35,998.06,801.15,0.10,490.86,131.85,0.15,199.44,235.36,2.56,485.78,23.10,0.15,199.80,596.27,400.48,29.09,1039.60,0.29
min,1000.00,685.28,159.21,0.05,1175.57,-999.00,0.10,0.00,0.00,1.00,0.00,20.00,0.00,0.00,1000.00,300.00,0.10,0.00,0.00
25%,1248.75,3354.75,2473.20,0.14,2481.96,645.00,0.23,375.34,234.78,3.00,674.01,38.75,0.00,361.56,1807.24,933.53,25.10,144.96,0.00
50%,1496.50,4002.89,3023.81,0.23,2822.28,679.00,0.35,508.57,388.08,5.00,1010.48,60.00,0.00,496.34,2215.70,1213.60,48.70,1032.81,0.00
75%,1749.00,4650.16,3555.50,0.31,3131.00,713.00,0.48,638.47,559.84,7.00,1337.82,79.00,0.00,640.10,2624.68,1482.86,76.10,1821.51,0.00
max,1999.00,7407.94,5853.20,0.40,4386.50,847.00,0.60,1176.88,1292.30,9.00,2585.36,99.00,1.00,1158.74,4245.90,2614.62,100.00,6589.66,1.00